---
markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: "/news/:year/:month/:day/:title/"
excerpt_separator: ''
gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1
repository: https://github.com/zachharkey/canopyrising
help_url: https://github.com/zachharkey/canopyrising
collections:
  docs:
    output: true
sass:
  style: compressed
